Repository dwyl/github-backup, pull requests merged in 2018-03, with the labels that each got.

#39 #38 Fixes comment width on wider screens
  assets/css/app.css
Labels: question

#41 New issue
  config/dev.exs
  config/prod.exs
  config/test.exs
  coveralls.json
  lib/app/comment.ex
  lib/app/issue.ex
  lib/app/version.ex
  lib/app_web/controllers/aws/in_memory.ex
  lib/app_web/controllers/aws/s3.ex
  lib/app_web/controllers/event_controller.ex
  lib/app_web/controllers/event_type.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20180301152611_create_issues.exs
  priv/repo/migrations/20180302100111_create_comments.exs
  priv/repo/migrations/20180302120058_create_version.exs
  test/app_web/controllers/event_controller_test.exs
  test/app_web/controllers/event_type_test.exs
  test/fixtures/issue_opened.json
Labels: in-review

#44 Edited issue
  lib/app/comment.ex
  lib/app/issue.ex
  lib/app/version.ex
  lib/app_web/controllers/aws/in_memory.ex
  lib/app_web/controllers/aws/s3.ex
  lib/app_web/controllers/event_controller.ex
  test/app_web/controllers/event_controller_test.exs
  test/fixtures/issue_edited.json
  test/fixtures/issue_title_edited.json
Labels: in-review

#48 Save new comment
  lib/app_web/controllers/event_controller.ex
  test/app_web/controllers/event_controller_test.exs
  test/fixtures/comment_created.json
Labels: in-review

#51 Edit comment
  lib/app_web/controllers/event_controller.ex
  test/app_web/controllers/event_controller_test.exs
  test/fixtures/comment_edited.json
Labels: in-review

#49 #47 Displays versions of a comment
  .travis.yml
  assets/static/images/user_avatar.png
  lib/app_web/controllers/aws/s3.ex
  lib/app_web/controllers/comment_controller.ex
  lib/app_web/router.ex
  lib/app_web/templates/comment/index.html.eex
  lib/app_web/views/comment_view.ex
  mix.lock
  test/app_web/controllers/comment_controller_test.exs
Labels: in-review

#57 #56 Reverts truncate fn for elixir v1.5
  lib/app_web/views/comment_view.ex
Labels: awaiting-review

#68 #53 Display markdown
  lib/app_web/controllers/aws/in_memory.ex
  lib/app_web/templates/comment/index.html.eex
  lib/app_web/views/comment_view.ex
  mix.exs
  mix.lock
Labels: in-review

#67 #58 Delete comment
  lib/app/comment.ex
  lib/app_web/controllers/event_controller.ex
  lib/app_web/controllers/event_type.ex
  lib/app_web/controllers/event_type_handlers.ex
  lib/app_web/templates/comment/index.html.eex
  priv/repo/migrations/20180307123903_add_deleted_column.exs
  test/app_web/controllers/event_controller_test.exs
  test/app_web/controllers/event_type_test.exs
  test/fixtures/comment_deleted.json
Labels: in-review

#74 #73 Removes default padding from markdown elements
  assets/css/app.css
  lib/app_web/templates/comment/index.html.eex
Labels: in-review

#80 Meta table
  README.md
  assets/static/images/edit_count.svg
  config/config.exs
  lib/app_web/controllers/edit_count_controller.ex
  lib/app_web/controllers/event_type_handlers.ex
  lib/app_web/controllers/github_api/http_client.ex
  lib/app_web/controllers/github_api/in_memory.ex
  lib/app_web/controllers/meta_table.ex
  lib/app_web/router.ex
  test/app_web/controllers/edit_count_controller_test.exs
Labels: in-review

#89 catch unknown event
  lib/app_web/controllers/event_type.ex
  lib/app_web/controllers/event_type_handlers.ex
  test/app_web/controllers/event_controller_test.exs
  test/fixtures/integration_installation.json
Labels: in-review

#97 #69 Renders markdown checkboxes as checkboxes
  lib/app_web/helpers/view.ex
  mix.exs
  mix.lock
  test/app_web/helpers/view_test.exs
Labels: in-review

#96 Update inserted at
  lib/app/comment.ex
  lib/app/helpers/issue.ex
  lib/app/issue.ex
  lib/app/version.ex
  lib/app_web/controllers/event_type_handlers.ex
  lib/app_web/templates/comment/index.html.eex
  lib/app_web/templates/issue/index.html.eex
  test/app_web/helpers/issue_test.exs
Labels: in-review

#99 save users in postgres
  lib/app/comment.ex
  lib/app/helpers/issue.ex
  lib/app/helpers/user.ex
  lib/app/issue.ex
  lib/app/user.ex
  lib/app/version.ex
  lib/app_web/controllers/event_type_handlers.ex
  lib/app_web/controllers/github_api/in_memory.ex
  lib/app_web/controllers/issue_controller.ex
  lib/app_web/templates/issue/index.html.eex
  priv/repo/migrations/20180315082449_create_users.exs
  priv/repo/migrations/20180315100012_add_references_user.exs
  test/app_web/controllers/comment_controller_test.exs
  test/app_web/controllers/edit_count_controller_test.exs
  test/app_web/controllers/issue_controller_test.exs
  test/app_web/helpers/issue_test.exs
  test/fixtures/user.json
Labels: in-review

#100 #70 Saves closed issue event in the DB and displays it on the front end
  lib/app/issue.ex
  lib/app/issue_status.ex
  lib/app_web/controllers/event_type.ex
  lib/app_web/controllers/event_type_handlers.ex
  lib/app_web/controllers/github_api/in_memory.ex
  lib/app_web/controllers/issue_controller.ex
  lib/app_web/templates/issue/index.html.eex
  priv/repo/migrations/20180315145533_issue_status.exs
  test/app_web/controllers/event_controller_test.exs
  test/app_web/controllers/issue_controller_test.exs
  test/fixtures/issue_closed.json
Labels: in-review

#105 #104 Homepage
  assets/css/app.css
  lib/app_web/helpers/view.ex
  lib/app_web/templates/comment/index.html.eex
  lib/app_web/templates/issue/index.html.eex
  lib/app_web/templates/layout/app.html.eex
  lib/app_web/templates/page/index.html.eex
  test/app_web/helpers/view_test.exs
Labels: awaiting-review

#103 #71 Creates Issue reopened event
  lib/app_web/controllers/event_type.ex
  lib/app_web/controllers/event_type_handlers.ex
  lib/app_web/controllers/issue_controller.ex
  lib/app_web/templates/issue/index.html.eex
  test/app_web/controllers/event_controller_test.exs
  test/app_web/controllers/issue_controller_test.exs
  test/fixtures/issue_reopened.json
Labels: awaiting-review

#109 Save state pr
  lib/app_web/controllers/event_type.ex
  lib/app_web/controllers/event_type_handlers.ex
  test/app_web/controllers/event_controller_test.exs
  test/fixtures/pr_closed.json
  test/fixtures/pr_reopened.json
Labels: awaiting-review

#64 Improve readme instructions issue#35
  .env_sample
  .gitignore
  README.md
  assets/README.md
  assets/package.json
Labels: awaiting-review, enhancement, in-review
